### ISSUE TITLE
LED Tower PCB

### ISSUE THREAD

**Issue by AndrewBunn00** [MaltWhiskey/Mega-Cube#10]
Hello! 
I'm making the Mega Cube currently, and would love to see some photos of the underside of one of the 16 pcb's for the towers. In the video, you show the underside of a completed one but it doesn't appear to match the final design you settled on (which the wiring is shown as a drawing right after). I'm newer to the hardware/electrical side of things, so a photo showing how things were laid out and what wire was used in the final design would be much appreciated :)

If you're curious, I've made 2 ladders of led's and am starting 2 more now. Wanting to get the first pcb finished so I can hook it up and test the first tower! 
![IMG_1034](https://github.com/MaltWhiskey/Mega-Cube/assets/89755834/f99902bd-535a-4a67-9c9d-19c9fd6a0edb)

**Comment by MaltWhiskey** [comment]
[image0.jpeg]
Using stranded wire (i think 14 awg) is much easier than solid core. Be mindful of the  isolation as to not short the circuit. You don’t need the dupont wire. Measure how long you want the wire with the xt-60 connector, it needs to get to the underside of the big aluminium plate (or what ever you used) and connect to a matching xt-60 connected to a psu.

Op 23 apr 2024 om 02:50 heeft Andrew Bunn ***@***.***> het volgende geschreven:

﻿

Hello!
I'm making the Mega Cube currently, and would love to see some photos of the underside of one of the 16 pcb's for the towers. In the video, you show the underside of a completed one but it doesn't appear to match the final design you settled on (which the wiring is shown as a drawing right after). I'm newer to the hardware/electrical side of things, so a photo showing how things were laid out and what wire was used in the final design would be much appreciated :)

If you're curious, I've made 2 ladders of led's and am starting 2 more now. Wanting to get the first pcb finished so I can hook it up and test the first tower!
IMG_1034.jpeg (view on web)<https://github.com/MaltWhiskey/Mega-Cube/assets/89755834/f99902bd-535a-4a67-9c9d-19c9fd6a0edb>

**Comment by AndrewBunn00** [comment]
It looks like the image didn't upload successfully ([image0.jpeg]). Would appreciate a reupload :) And I went with an aluminum plate as well, my goal is to follow what you did as close as possible.

**Comment by MaltWhiskey** [comment]
![IMG_6447](https://github.com/MaltWhiskey/Mega-Cube/assets/45141238/2b2b7554-c1a8-4f3d-b1f0-f0a169c5555f)
![IMG_6449](https://github.com/MaltWhiskey/Mega-Cube/assets/45141238/68239b19-5f06-41d7-8397-686a9a2d1b96)

**Comment by MaltWhiskey** [comment]
I recommend using color coded jst rcy 2 pin connectors for the led channels (don’t use dupont). Makes sorting wires a lot easier.
