### ISSUE TITLE
Components 

### ISSUE THREAD

**Issue by TallKid420** [MaltWhiskey/Mega-Cube#2]
Can you please give me the order links to everything thanks

**Comment by khan-pog** [comment]
Hello here is a couple links to what i have found for PCB components.

ESP8266:
https://core-electronics.com.au/wifi-module-esp8266-4mb.html?utm_source=google_shopping&gclid=Cj0KCQiAhMOMBhDhARIsAPVml-Fc0lQ1HSQYuxgi_iO0l_lReAPuaQj5TYT0rrXmwo_W-QfPbNYd6dMaAqf6EALw_wcB

Teensy-4.0:
https://core-electronics.com.au/teensy-4-0.html?utm_source=google_shopping&gclid=Cj0KCQiAhMOMBhDhARIsAPVml-FsOR5mrNkSrcTn4CHY1SKsLt9gJQlMnYgvpmFuejGfpa787P3SYnkaAs4WEALw_wcB

Voltage regulator:
https://www.ebay.com.au/itm/304129516747?chn=ps&_trkparms=ispr%3D1&amdata=enc%3A1OaLXNLgRQxa9T5xn65Wg7g2&norover=1&mkevt=1&mkrid=705-139619-5960-0&mkcid=2&itemid=304129516747&targetid=1395035667576&device=c&mktype=pla&googleloc=1000414&poi=&campaignid=14475548384&mkgroupid=132282084371&rlsatarget=pla-1395035667576&abcId=9300653&merchantid=494523277&gclid=Cj0KCQiAhMOMBhDhARIsAPVml-HFyIFPKYzbJQr7sBZLEh_8ElimrUIwVuaRg9FkWNS-dQQkxUJ2oDYaAu2gEALw_wcB

2.4 inch screen and sd card.
https://www.ebay.com.au/itm/322638960113

Addressable LED WS2811:
https://de.aliexpress.com/item/32832099662.html?src=google&src=google&memo1=freelisting&albch=shopping&acnt=708-803-3821&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=11482541945&albag=112620152352&trgt=294682000766&crea=en32832099662&netw=u&device=c&albpg=294682000766&albpd=en32832099662&gclid=Cj0KCQiAhMOMBhDhARIsAPVml-EbNVDB2QLVDybrTTQwC61qjBjJSCwCofuk9nKdNkCwJKln_l34CbEaAtlqEALw_wcB&gclsrc=aw.ds&aff_fcid=3860720e469d46d2a8698c2825cf917c-1636882299468-09532-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=3860720e469d46d2a8698c2825cf917c-1636882299468-09532-UneMJZVf&terminal_id=1e017a344b5b4ffb8b43762bf2677892

**Comment by TallKid420** [comment]
Thank you for sending these it helped a lot

**Comment by MaltWhiskey** [comment]
Get pl9823 5mm leds not ws281x unless you first test a few and they work without capacitor.
The pcb has an assembly file, it’s in excel format for windows or numbers for ios. If you use the assembly file with assembly service the fab company will assemble the board for you with the components placed. The kicad project will also reveal all connectors and components used, there are no secrets here.
I used silvered copper wire 0.8mm, but copper will be fine too. If you don’t have a draw plate, get 0.6 or 0.65 mm instead.
12 AWG silicone wire, xt60 connectors. (Use what you like, there is only around 16A each tower so xt60 is overkill, but i like them a lot better than xt30.
The screen is ili9341 2.4”.
The connectors are for nixitube sockets, they are a bit bigger than pin headers.

If you are going to make this COOL!!!
